// script.js

document.getElementById("sortearBtn").addEventListener("click", function () {
    const nomes = [
        "A bicicleta",
        "Cara a cara",
        "O plugue",
        "O cachorro",
        "Pequena conchinha",
        "69 em ponte",
        "O gato",
        "A cascata",
        "Na subida",
        "Cow Girl",
        "Cadeira quente",
        "No topo",
        "Caminho para o céu",
        "Cow Girl invertida",
        "O varão",
        "O preguiçoso",
        "David Copperfield",
        "O trono",
        "Fechar o negócio",
        "Pretzel",
        "A estante",
        "O G",
        "Cão",
        "Fazer manteiga",
        "A bailarina",
        "O chef",
        "H20",
        "Carrinho de mão",
        "Carrinho de mão sentado",
        "O dragão",
        "Serviço de quarto",
        "Surfista",
        "Solução rápida",
        "Mountain climbers",
        "Missionário viciado",
        "Missionário",
        "Conchinha",
        "Spork",
        "Presente embrulhado",
        "Conchinha cara-a-cara",
        "o X",
        "Fusão",
        "A aranha",
        "Mariposa",
        "69",
        "Libélula",
        "O elevador",
        "Torpedo Suíço",
        "O estandarte"
    ];
    const nomeSorteado = nomes[Math.floor(Math.random() * nomes.length)];
    document.getElementById("resultado").textContent = `Posição sorteada: ${nomeSorteado}`;
});
